packages:
  - apps/*
  - packages/*

catalog:
  '@chromatic-com/storybook': ^5.0.1
  '@storybook/addon-a11y': ^10.2.17
  '@storybook/addon-docs': ^10.2.17
  '@storybook/addon-onboarding': ^10.2.17
  '@storybook/react-vite': ^10.2.17
  '@stzhu/eslint-config': ^0.10.0
  '@stzhu/prettier-plugin-tsconfig': ^0.7.1
  '@stzhu/tsconfig': ^0.3.0
  '@types/node': ^25.4.0
  '@types/react': ^19.2.14
  '@types/react-dom': ^19.2.3
  electron: ^40.6.0
  eslint: ^10.0.0
  hono: ^4.12.7
  react: ^19.2.4
  react-dom: ^19.2.4
  storybook: ^10.2.17
  tailwindcss: ^4.2.1
  typescript: ^5.9.3
  vite: ^7.3.1
  vitest: ^4.0.18

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - electron
  - electron-winstaller
  - esbuild
  - msw
  - sharp
  - spawn-sync
  - tldjs
  - unrs-resolver
  - workerd

overrides:
  react-refresh: ^0.18.0
  # TODO: fix workos lib versions
  # '@workos-inc/authkit-react': ^0.16.0
  # '@workos-inc/node': ^8.0.0

packageExtensions:
  lucide-react:
    peerDependencies:
      '@types/react': ^19
  react-day-picker:
    peerDependencies:
      '@types/react': ^19

patchedDependencies:
  '@electron-toolkit/typed-ipc': patches/@electron-toolkit__typed-ipc.patch
  electron-vite: patches/electron-vite.patch

saveWorkspaceProtocol: rolling

strictDepBuilds: true
